using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GymSharp.ressources.enums
{
    public enum Exercice
    {
        Developpes_couche = 11,
        Developpes_incline = 12,
        Developpes_decline = 13,
        Ecarte_halteres = 14,
        Ecarte_poulies = 15,
        Pec_deck = 16,
        Pompe = 17,
        Traction = 21,
        Rowing = 22,
        Shrug = 23,
        Tirages_verticaux = 24,
        Tirage_horizontaux = 25,
        Extension_lombaire = 26,
        Pullover = 27,
        Shrug_incline_halteres = 28,
        Rowing_barre_t = 29,
        Rowing_haltre = 210,
        Tirage_horizontal_haut = 211,
        Rowing_deux_halteres = 212,
        Curls_a_la_barre = 31,
        Curls_halteres = 32,
        Curls_poulie = 33,
        Dips = 34,
        Kickback = 35,
        Developpes_a_la_barre = 36,
        Extension_assis = 37,
        Extension_couche = 38,
        Extension_a_la_poulie = 39,
        Flexion_aux_halteres = 310,
        Flexion_barre_pronation = 311,
        Flexion_barre_supination = 312,
        Developpes_epaules = 41,
        Elevation_laterale = 42,
        Elevation_frontale = 43,
        Elevation_buste_penche = 44,
        Tirage_menton = 45,
        Rowing_assis = 46,
        Oiseau_a_la_poulie = 47,
        Elevation_frontales_incline = 48,
        Crunch = 51,
        Crunch_a_la_poulie = 52,
        Gainage = 53,
        Releves_de_jambes = 54,
        Flexions_laterales = 55,
        Rotation_avec_baton = 56,
        Squat = 61,
        Leg_extension = 62,
        Hack_squat = 63,
        Presse_a_cuisse = 64,
        Squat_barre_guidee = 65,
        Montee_sur_banc = 66,
        Sissy_squat = 67,
        Souleve_de_terre_jambes_tendues = 71,
        Leg_curl_debout = 72,
        Good_morning = 73,
        Leg_curl_assis = 74,
        Fentes = 75,
        Mollets_a_la_presse = 81,
        Elevation_a_45 = 82,
        Mollets_assis = 83,
        Mollets_debout = 84
    }
}
