using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GymSharp.ressources.enums
{
    public enum Exercice
    {
        Developpes_couche = 11,
        Developpes_incline = 12,
        Developpes_decline = 13,
        Ecarte_halteres = 14,
        Ecarte_poulies = 15,
        Pec_deck = 16,
        Pompe = 17,
        Traction = 21,
        Rowing = 22,
        Shrug = 23,
        Tirages_verticaux = 24,
        Tirage_horizontaux = 25,
        Extension_lombaire = 26,
        Pullover = 27,
        shrug_incline_halteres = 28,
        Rowing_barre_t = 29,
        Rowing_haltre = 210,
        Tirage_horizontal_haut = 211,
        Rowing_deux_halteres = 212,
        Curls_a_la_barre = 31,
        Curls_halteres = 32,
        Curls_poulie = 33,
        Dips = 41,
        Kickback = 42,
        Developpes_a_la_barre = 43,
        Extension_assis = 44,
        Extension_couche = 45,
        Extension_a_la_poulie = 46,
        Developpes_epaules = 51,
        Elevation_laterale = 52,
        Elevation_frontale = 53,
        Elevation_buste_penche = 54,
        Tirage_menton = 55,
        Rowing_assis = 56,
        Oiseau_a_la_poulie = 57,
        Elevation_frontales_incline = 58,
        Crunch = 61,
        Crunch_a_la_poulie = 62,
        Gainage = 63,
        Releves_de_jambes = 64,
        Flexions_laterales = 65,
        Rotation_avec_baton = 66,
        Squat = 71,
        Leg_extension = 72,
        Hack_squat = 73,
        Presse_a_cuisse = 74,
        Squat_barre_guidee = 75,
        Montee_sur_banc = 76,
        Sissy_squat = 77,
        Souleve_de_terre_jambes_tendues = 81,
        Leg_curl_debout = 82,
        Good_morning = 83,
        Leg_curl_assis = 84,
        Fentes = 85,
        Mollets_a_la_presse = 91,
        Elevation_a_45 = 92,
        Mollets_assis = 93,
        Mollets_debout = 94,
        Flexion_aux_halteres = 101,
        Flexion_barre_pronation = 102,
        Flexion_barre_supination = 103,
    }
}
